# -*- coding: utf-8 -*-
"""exception_handling_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q_sV1y6RkgqUe2MXoMs4ClIRAnN0c74m
"""

import logging

a=int(input("enter the first value"))
b=int(input("enter the first value"))

try:
    x=a/b
except ZeroDivisionError as e :
  print ('sorry')

else: print (x)
finally:
  print("thank you")